diff --git a/Makefile b/Makefile
index 677f2ec..77d4aff 100644
--- a/Makefile
+++ b/Makefile
@@ -36,7 +36,7 @@
 
 PROJECT_NAME   = hyperledger/fabric
 BASE_VERSION   = 1.0.0
-IS_RELEASE     = false
+IS_RELEASE     = true
 
 ifneq ($(IS_RELEASE),true)
 EXTRA_VERSION ?= snapshot-$(shell git rev-parse --short HEAD)
@@ -178,8 +178,8 @@ build/docker/gotools: gotools/Makefile
 		make install BINDIR=/opt/gotools/bin OBJDIR=/opt/gotools/obj
 
 # Both peer and peer-docker depend on ccenv and javaenv (all docker env images it supports).
-build/bin/peer: build/image/ccenv/$(DUMMY) build/image/javaenv/$(DUMMY)
-build/image/peer/$(DUMMY): build/image/ccenv/$(DUMMY) build/image/javaenv/$(DUMMY)
+build/bin/peer: build/image/ccenv/$(DUMMY) 
+build/image/peer/$(DUMMY): build/image/ccenv/$(DUMMY) 
 
 build/bin/%: $(PROJECT_FILES)
 	@mkdir -p $(@D)
@@ -191,26 +191,26 @@ build/bin/%: $(PROJECT_FILES)
 # payload definitions'
 build/image/ccenv/payload:      build/docker/gotools/bin/protoc-gen-go \
 				build/bin/chaintool \
-				build/goshim.tar.bz2
-build/image/javaenv/payload:    build/javashim.tar.bz2 \
-				build/protos.tar.bz2 \
+				build/goshim.tar
+build/image/javaenv/payload:    build/javashim.tar \
+				build/protos.tar \
 				settings.gradle
 build/image/peer/payload:       build/docker/bin/peer \
 				peer/core.yaml \
-				build/msp-sampleconfig.tar.bz2 \
+				build/msp-sampleconfig.tar \
 				common/configtx/tool/configtx.yaml
 build/image/orderer/payload:    build/docker/bin/orderer \
-				build/msp-sampleconfig.tar.bz2 \
+				build/msp-sampleconfig.tar \
 				orderer/orderer.yaml \
 				common/configtx/tool/configtx.yaml
-build/image/buildenv/payload:   build/gotools.tar.bz2 \
+build/image/buildenv/payload:   build/gotools.tar \
 				build/docker/gotools/bin/protoc-gen-go
 build/image/testenv/payload:    build/docker/bin/orderer \
 				orderer/orderer.yaml \
 				common/configtx/tool/configtx.yaml \
 				build/docker/bin/peer \
 				peer/core.yaml \
-				build/msp-sampleconfig.tar.bz2 \
+				build/msp-sampleconfig.tar \
 				images/testenv/install-softhsm2.sh
 build/image/zookeeper/payload:  images/zookeeper/docker-entrypoint.sh
 build/image/kafka/payload:      images/kafka/docker-entrypoint.sh \
@@ -240,20 +240,20 @@ build/image/%/$(DUMMY): Makefile build/image/%/payload build/image/%/Dockerfile
 	docker tag $(PROJECT_NAME)-$(TARGET) $(PROJECT_NAME)-$(TARGET):$(DOCKER_TAG)
 	@touch $@
 
-build/gotools.tar.bz2: build/docker/gotools
-	(cd $</bin && tar -jc *) > $@
+build/gotools.tar: build/docker/gotools
+	(cd $</bin && tar -c *) > $@
 
-build/goshim.tar.bz2: $(GOSHIM_DEPS)
+build/goshim.tar: $(GOSHIM_DEPS)
 	@echo "Creating $@"
-	@tar -jhc -C $(GOPATH)/src $(patsubst $(GOPATH)/src/%,%,$(GOSHIM_DEPS)) > $@
+	@tar -hc -C $(GOPATH)/src $(patsubst $(GOPATH)/src/%,%,$(GOSHIM_DEPS)) > $@
 
-build/javashim.tar.bz2: $(JAVASHIM_DEPS)
-build/protos.tar.bz2: $(PROTOS)
-build/msp-sampleconfig.tar.bz2: $(MSP_SAMPLECONFIG)
+build/javashim.tar: $(JAVASHIM_DEPS)
+build/protos.tar: $(PROTOS)
+build/msp-sampleconfig.tar: $(MSP_SAMPLECONFIG)
 
-build/%.tar.bz2:
+build/%.tar:
 	@echo "Creating $@"
-	@tar -jc $^ > $@
+	@tar -c $^ > $@
 
 .PHONY: protos
 protos: buildenv
diff --git a/images/buildenv/Dockerfile.in b/images/buildenv/Dockerfile.in
index 7bdd13f..b4526f8 100644
--- a/images/buildenv/Dockerfile.in
+++ b/images/buildenv/Dockerfile.in
@@ -1,3 +1,3 @@
 FROM hyperledger/fabric-baseimage:_BASE_TAG_
 COPY payload/protoc-gen-go /usr/local/bin/
-ADD payload/gotools.tar.bz2 /usr/local/bin/
+ADD payload/gotools.tar /usr/local/bin/
diff --git a/images/ccenv/Dockerfile.in b/images/ccenv/Dockerfile.in
index 06700f7..ef55edb 100644
--- a/images/ccenv/Dockerfile.in
+++ b/images/ccenv/Dockerfile.in
@@ -1,4 +1,4 @@
 FROM hyperledger/fabric-baseimage:_BASE_TAG_
 COPY payload/chaintool payload/protoc-gen-go /usr/local/bin/
-ADD payload/goshim.tar.bz2 $GOPATH/src/
+ADD payload/goshim.tar $GOPATH/src/
 RUN mkdir -p /chaincode/input /chaincode/output
diff --git a/images/javaenv/Dockerfile.in b/images/javaenv/Dockerfile.in
index d7a7804..36ce123 100644
--- a/images/javaenv/Dockerfile.in
+++ b/images/javaenv/Dockerfile.in
@@ -10,8 +10,8 @@ RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
   && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
 ENV MAVEN_HOME /usr/share/maven
 ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"
-ADD payload/javashim.tar.bz2 /root
-ADD payload/protos.tar.bz2 /root
+ADD payload/javashim.tar /root
+ADD payload/protos.tar /root
 ADD payload/settings.gradle /root
 WORKDIR /root
 # Build java shim after copying proto files from fabric/proto
diff --git a/images/orderer/Dockerfile.in b/images/orderer/Dockerfile.in
index 711f34a..907c6f6 100644
--- a/images/orderer/Dockerfile.in
+++ b/images/orderer/Dockerfile.in
@@ -6,6 +6,6 @@ RUN mkdir -p /var/hyperledger/production $ORDERER_CFG_PATH
 COPY payload/orderer /usr/local/bin
 COPY payload/configtx.yaml $ORDERER_CFG_PATH/
 COPY payload/orderer.yaml $ORDERER_CFG_PATH/
-ADD payload/msp-sampleconfig.tar.bz2 $ORDERER_CFG_PATH/
+ADD payload/msp-sampleconfig.tar $ORDERER_CFG_PATH/
 EXPOSE 7050
 CMD ["orderer"]
diff --git a/images/peer/Dockerfile.in b/images/peer/Dockerfile.in
index cff0dfb..d53b71f 100644
--- a/images/peer/Dockerfile.in
+++ b/images/peer/Dockerfile.in
@@ -4,6 +4,6 @@ ENV CORE_PEER_MSPCONFIGPATH $PEER_CFG_PATH/msp/sampleconfig
 RUN mkdir -p /var/hyperledger/production $PEER_CFG_PATH
 COPY payload/peer /usr/local/bin
 COPY payload/core.yaml $PEER_CFG_PATH
-ADD  payload/msp-sampleconfig.tar.bz2 $PEER_CFG_PATH
+ADD  payload/msp-sampleconfig.tar $PEER_CFG_PATH
 ADD  payload/configtx.yaml $PEER_CFG_PATH
 CMD ["peer","node","start"]
diff --git a/images/testenv/Dockerfile.in b/images/testenv/Dockerfile.in
index 5e88f84..9d91809 100644
--- a/images/testenv/Dockerfile.in
+++ b/images/testenv/Dockerfile.in
@@ -15,7 +15,7 @@ RUN mkdir -p \
 COPY payload/orderer.yaml $ORDERER_CFG_PATH
 COPY payload/configtx.yaml $ORDERER_CFG_PATH
 COPY payload/core.yaml $PEER_CFG_PATH
-ADD payload/msp-sampleconfig.tar.bz2 $PEER_CFG_PATH
+ADD payload/msp-sampleconfig.tar $PEER_CFG_PATH
 
 # fabric binaries
 COPY payload/orderer /usr/local/bin
