// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer/chaincode.proto

package peer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Confidentiality Levels
type ConfidentialityLevel int32

const (
	ConfidentialityLevel_PUBLIC       ConfidentialityLevel = 0
	ConfidentialityLevel_CONFIDENTIAL ConfidentialityLevel = 1
)

var ConfidentialityLevel_name = map[int32]string{
	0: "PUBLIC",
	1: "CONFIDENTIAL",
}
var ConfidentialityLevel_value = map[string]int32{
	"PUBLIC":       0,
	"CONFIDENTIAL": 1,
}

func (x ConfidentialityLevel) String() string {
	return proto.EnumName(ConfidentialityLevel_name, int32(x))
}
func (ConfidentialityLevel) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type ChaincodeSpec_Type int32

const (
	ChaincodeSpec_UNDEFINED  ChaincodeSpec_Type = 0
	ChaincodeSpec_GOLANG     ChaincodeSpec_Type = 1
	ChaincodeSpec_NODE       ChaincodeSpec_Type = 2
	ChaincodeSpec_CAR        ChaincodeSpec_Type = 3
	ChaincodeSpec_JAVA       ChaincodeSpec_Type = 4
	ChaincodeSpec_JAVASCRIPT ChaincodeSpec_Type = 5
)

var ChaincodeSpec_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "GOLANG",
	2: "NODE",
	3: "CAR",
	4: "JAVA",
	5: "JAVASCRIPT",
}
var ChaincodeSpec_Type_value = map[string]int32{
	"UNDEFINED":  0,
	"GOLANG":     1,
	"NODE":       2,
	"CAR":        3,
	"JAVA":       4,
	"JAVASCRIPT": 5,
}

func (x ChaincodeSpec_Type) String() string {
	return proto.EnumName(ChaincodeSpec_Type_name, int32(x))
}
func (ChaincodeSpec_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

type ChaincodeDeploymentSpec_ExecutionEnvironment int32

const (
	ChaincodeDeploymentSpec_DOCKER      ChaincodeDeploymentSpec_ExecutionEnvironment = 0
	ChaincodeDeploymentSpec_SYSTEM      ChaincodeDeploymentSpec_ExecutionEnvironment = 1
	ChaincodeDeploymentSpec_INTERPRETER ChaincodeDeploymentSpec_ExecutionEnvironment = 2
)

var ChaincodeDeploymentSpec_ExecutionEnvironment_name = map[int32]string{
	0: "DOCKER",
	1: "SYSTEM",
	2: "INTERPRETER",
}
var ChaincodeDeploymentSpec_ExecutionEnvironment_value = map[string]int32{
	"DOCKER":      0,
	"SYSTEM":      1,
	"INTERPRETER": 2,
}

func (x ChaincodeDeploymentSpec_ExecutionEnvironment) String() string {
	return proto.EnumName(ChaincodeDeploymentSpec_ExecutionEnvironment_name, int32(x))
}
func (ChaincodeDeploymentSpec_ExecutionEnvironment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 0}
}

// ChaincodeID contains the path as specified by the deploy transaction
// that created it as well as the hashCode that is generated by the
// system for the path. From the user level (ie, CLI, REST API and so on)
// deploy transaction is expected to provide the path and other requests
// are expected to provide the hashCode. The other value will be ignored.
// Internally, the structure could contain both values. For instance, the
// hashCode will be set when first generated using the path
type ChaincodeID struct {
	// deploy transaction will use the path
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	// all other requests will use the name (really a hashcode) generated by
	// the deploy transaction
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// user friendly version name for the chaincode
	Version string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (m *ChaincodeID) Reset()                    { *m = ChaincodeID{} }
func (m *ChaincodeID) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeID) ProtoMessage()               {}
func (*ChaincodeID) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ChaincodeID) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ChaincodeID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChaincodeID) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Carries the chaincode function and its arguments.
// UnmarshalJSON in transaction.go converts the string-based REST/JSON input to
// the []byte-based current ChaincodeInput structure.
type ChaincodeInput struct {
	Args [][]byte `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
}

func (m *ChaincodeInput) Reset()                    { *m = ChaincodeInput{} }
func (m *ChaincodeInput) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeInput) ProtoMessage()               {}
func (*ChaincodeInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ChaincodeInput) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

// Carries the chaincode specification. This is the actual metadata required for
// defining a chaincode.
type ChaincodeSpec struct {
	Type        ChaincodeSpec_Type `protobuf:"varint,1,opt,name=type,enum=protos.ChaincodeSpec_Type" json:"type,omitempty"`
	ChaincodeId *ChaincodeID       `protobuf:"bytes,2,opt,name=chaincode_id,json=chaincodeId" json:"chaincode_id,omitempty"`
	Input       *ChaincodeInput    `protobuf:"bytes,3,opt,name=input" json:"input,omitempty"`
	Timeout     int32              `protobuf:"varint,4,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *ChaincodeSpec) Reset()                    { *m = ChaincodeSpec{} }
func (m *ChaincodeSpec) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeSpec) ProtoMessage()               {}
func (*ChaincodeSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ChaincodeSpec) GetType() ChaincodeSpec_Type {
	if m != nil {
		return m.Type
	}
	return ChaincodeSpec_UNDEFINED
}

func (m *ChaincodeSpec) GetChaincodeId() *ChaincodeID {
	if m != nil {
		return m.ChaincodeId
	}
	return nil
}

func (m *ChaincodeSpec) GetInput() *ChaincodeInput {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *ChaincodeSpec) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

// Specify the deployment of a chaincode.
// TODO: Define `codePackage`.
type ChaincodeDeploymentSpec struct {
	ChaincodeSpec *ChaincodeSpec `protobuf:"bytes,1,opt,name=chaincode_spec,json=chaincodeSpec" json:"chaincode_spec,omitempty"`
	// Controls when the chaincode becomes executable.
	EffectiveDate *google_protobuf1.Timestamp                  `protobuf:"bytes,2,opt,name=effective_date,json=effectiveDate" json:"effective_date,omitempty"`
	CodePackage   []byte                                       `protobuf:"bytes,3,opt,name=code_package,json=codePackage,proto3" json:"code_package,omitempty"`
	ExecEnv       ChaincodeDeploymentSpec_ExecutionEnvironment `protobuf:"varint,4,opt,name=exec_env,json=execEnv,enum=protos.ChaincodeDeploymentSpec_ExecutionEnvironment" json:"exec_env,omitempty"`
}

func (m *ChaincodeDeploymentSpec) Reset()                    { *m = ChaincodeDeploymentSpec{} }
func (m *ChaincodeDeploymentSpec) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeDeploymentSpec) ProtoMessage()               {}
func (*ChaincodeDeploymentSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ChaincodeDeploymentSpec) GetChaincodeSpec() *ChaincodeSpec {
	if m != nil {
		return m.ChaincodeSpec
	}
	return nil
}

func (m *ChaincodeDeploymentSpec) GetEffectiveDate() *google_protobuf1.Timestamp {
	if m != nil {
		return m.EffectiveDate
	}
	return nil
}

func (m *ChaincodeDeploymentSpec) GetCodePackage() []byte {
	if m != nil {
		return m.CodePackage
	}
	return nil
}

func (m *ChaincodeDeploymentSpec) GetExecEnv() ChaincodeDeploymentSpec_ExecutionEnvironment {
	if m != nil {
		return m.ExecEnv
	}
	return ChaincodeDeploymentSpec_DOCKER
}

// Carries the chaincode function and its arguments.
type ChaincodeInvocationSpec struct {
	ChaincodeSpec *ChaincodeSpec `protobuf:"bytes,1,opt,name=chaincode_spec,json=chaincodeSpec" json:"chaincode_spec,omitempty"`
	// This field can contain a user-specified ID generation algorithm
	// If supplied, this will be used to generate a ID
	// If not supplied (left empty), sha256base64 will be used
	// The algorithm consists of two parts:
	//  1, a hash function
	//  2, a decoding used to decode user (string) input to bytes
	// Currently, SHA256 with BASE64 is supported (e.g. idGenerationAlg='sha256base64')
	IdGenerationAlg string `protobuf:"bytes,2,opt,name=id_generation_alg,json=idGenerationAlg" json:"id_generation_alg,omitempty"`
}

func (m *ChaincodeInvocationSpec) Reset()                    { *m = ChaincodeInvocationSpec{} }
func (m *ChaincodeInvocationSpec) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeInvocationSpec) ProtoMessage()               {}
func (*ChaincodeInvocationSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ChaincodeInvocationSpec) GetChaincodeSpec() *ChaincodeSpec {
	if m != nil {
		return m.ChaincodeSpec
	}
	return nil
}

func (m *ChaincodeInvocationSpec) GetIdGenerationAlg() string {
	if m != nil {
		return m.IdGenerationAlg
	}
	return ""
}

func init() {
	proto.RegisterType((*ChaincodeID)(nil), "protos.ChaincodeID")
	proto.RegisterType((*ChaincodeInput)(nil), "protos.ChaincodeInput")
	proto.RegisterType((*ChaincodeSpec)(nil), "protos.ChaincodeSpec")
	proto.RegisterType((*ChaincodeDeploymentSpec)(nil), "protos.ChaincodeDeploymentSpec")
	proto.RegisterType((*ChaincodeInvocationSpec)(nil), "protos.ChaincodeInvocationSpec")
	proto.RegisterEnum("protos.ConfidentialityLevel", ConfidentialityLevel_name, ConfidentialityLevel_value)
	proto.RegisterEnum("protos.ChaincodeSpec_Type", ChaincodeSpec_Type_name, ChaincodeSpec_Type_value)
	proto.RegisterEnum("protos.ChaincodeDeploymentSpec_ExecutionEnvironment", ChaincodeDeploymentSpec_ExecutionEnvironment_name, ChaincodeDeploymentSpec_ExecutionEnvironment_value)
}

func init() { proto.RegisterFile("peer/chaincode.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x6f, 0xda, 0x4a,
	0x10, 0x8d, 0x81, 0x7c, 0x0d, 0x1f, 0xf1, 0xdd, 0x9b, 0x7b, 0x8b, 0xf2, 0xd2, 0xd4, 0xea, 0x43,
	0x1a, 0x55, 0x46, 0xa2, 0x51, 0x9f, 0x2a, 0x55, 0x04, 0x3b, 0x91, 0x5b, 0x6a, 0xd0, 0x42, 0x2a,
	0xb5, 0x2f, 0xc8, 0xd8, 0x83, 0x59, 0xd5, 0xec, 0x5a, 0xf6, 0x62, 0x85, 0xe7, 0xfe, 0x80, 0xfe,
	0xb4, 0xfe, 0xa5, 0x6a, 0xd7, 0x81, 0x24, 0x4a, 0x1e, 0xfb, 0xe4, 0xd9, 0xb3, 0x67, 0x66, 0xcf,
	0x1c, 0xcd, 0x18, 0x8e, 0x53, 0xc4, 0xac, 0x13, 0x2e, 0x02, 0xc6, 0x43, 0x11, 0xa1, 0x9d, 0x66,
	0x42, 0x0a, 0xb2, 0xa7, 0x3f, 0xf9, 0xc9, 0xcb, 0x58, 0x88, 0x38, 0xc1, 0x8e, 0x3e, 0xce, 0x56,
	0xf3, 0x8e, 0x64, 0x4b, 0xcc, 0x65, 0xb0, 0x4c, 0x4b, 0xa2, 0x35, 0x84, 0x7a, 0x7f, 0x93, 0xeb,
	0x39, 0x84, 0x40, 0x2d, 0x0d, 0xe4, 0xa2, 0x6d, 0x9c, 0x1a, 0x67, 0x87, 0x54, 0xc7, 0x0a, 0xe3,
	0xc1, 0x12, 0xdb, 0x95, 0x12, 0x53, 0x31, 0x69, 0xc3, 0x7e, 0x81, 0x59, 0xce, 0x04, 0x6f, 0x57,
	0x35, 0xbc, 0x39, 0x5a, 0xaf, 0xa1, 0x75, 0x5f, 0x90, 0xa7, 0x2b, 0xa9, 0xf2, 0x83, 0x2c, 0xce,
	0xdb, 0xc6, 0x69, 0xf5, 0xac, 0x41, 0x75, 0x6c, 0xfd, 0xaa, 0x40, 0x73, 0x4b, 0x1b, 0xa7, 0x18,
	0x12, 0x1b, 0x6a, 0x72, 0x9d, 0xa2, 0x7e, 0xb9, 0xd5, 0x3d, 0x29, 0xe5, 0xe5, 0xf6, 0x23, 0x92,
	0x3d, 0x59, 0xa7, 0x48, 0x35, 0x8f, 0xbc, 0x87, 0xc6, 0xb6, 0xe9, 0x29, 0x8b, 0xb4, 0xba, 0x7a,
	0xf7, 0xdf, 0x27, 0x79, 0x9e, 0x43, 0xeb, 0x5b, 0xa2, 0x17, 0x91, 0xb7, 0xb0, 0xcb, 0x94, 0x2c,
	0xad, 0xbb, 0xde, 0xfd, 0xff, 0x69, 0x82, 0xba, 0xa5, 0x25, 0x49, 0xf5, 0xa9, 0x1c, 0x13, 0x2b,
	0xd9, 0xae, 0x9d, 0x1a, 0x67, 0xbb, 0x74, 0x73, 0xb4, 0x7c, 0xa8, 0x29, 0x35, 0xa4, 0x09, 0x87,
	0x37, 0xbe, 0xe3, 0x5e, 0x79, 0xbe, 0xeb, 0x98, 0x3b, 0x04, 0x60, 0xef, 0x7a, 0x38, 0xe8, 0xf9,
	0xd7, 0xa6, 0x41, 0x0e, 0xa0, 0xe6, 0x0f, 0x1d, 0xd7, 0xac, 0x90, 0x7d, 0xa8, 0xf6, 0x7b, 0xd4,
	0xac, 0x2a, 0xe8, 0x53, 0xef, 0x6b, 0xcf, 0xac, 0x91, 0x16, 0x80, 0x8a, 0xc6, 0x7d, 0xea, 0x8d,
	0x26, 0xe6, 0xae, 0xf5, 0xbb, 0x02, 0x2f, 0xb6, 0x1a, 0x1c, 0x4c, 0x13, 0xb1, 0x5e, 0x22, 0x97,
	0xda, 0x9b, 0x0f, 0xd0, 0xba, 0xef, 0x35, 0x4f, 0x31, 0xd4, 0x2e, 0xd5, 0xbb, 0xff, 0x3d, 0xeb,
	0x12, 0x6d, 0x86, 0x8f, 0x9c, 0xed, 0x41, 0x0b, 0xe7, 0x73, 0x0c, 0x25, 0x2b, 0x70, 0x1a, 0x05,
	0x12, 0xef, 0xbc, 0x3a, 0xb1, 0xcb, 0xe1, 0xb0, 0x37, 0xc3, 0x61, 0x4f, 0x36, 0xc3, 0x41, 0x9b,
	0xdb, 0x0c, 0x27, 0x90, 0x48, 0x5e, 0x41, 0x43, 0xbf, 0x9d, 0x06, 0xe1, 0x8f, 0x20, 0x46, 0xed,
	0x5d, 0x83, 0xd6, 0x15, 0x36, 0x2a, 0x21, 0x32, 0x84, 0x03, 0xbc, 0xc5, 0x70, 0x8a, 0xbc, 0xd0,
	0x56, 0xb5, 0xba, 0x17, 0x4f, 0xd4, 0x3d, 0x6e, 0xcb, 0x76, 0x6f, 0x31, 0x5c, 0x49, 0x26, 0xb8,
	0xcb, 0x0b, 0x96, 0x09, 0xae, 0x2e, 0xe8, 0xbe, 0xaa, 0xe2, 0xf2, 0xc2, 0xfa, 0x08, 0xc7, 0xcf,
	0x11, 0x94, 0xc3, 0xce, 0xb0, 0xff, 0xd9, 0xa5, 0xa5, 0xdb, 0xe3, 0x6f, 0xe3, 0x89, 0xfb, 0xc5,
	0x34, 0xc8, 0x11, 0xd4, 0x3d, 0x7f, 0xe2, 0xd2, 0x11, 0x75, 0x27, 0x2e, 0x35, 0x2b, 0xd6, 0x4f,
	0xe3, 0x81, 0xa3, 0x1e, 0x2f, 0x44, 0x18, 0xa8, 0x5a, 0x7f, 0xc1, 0xd1, 0x73, 0xf8, 0x87, 0x45,
	0xd3, 0x18, 0x39, 0x66, 0xba, 0xe4, 0x34, 0x48, 0xe2, 0xbb, 0xf5, 0x38, 0x62, 0xd1, 0xf5, 0x16,
	0xef, 0x25, 0xf1, 0xf9, 0x05, 0x1c, 0xf7, 0x05, 0x9f, 0xb3, 0x08, 0xb9, 0x64, 0x41, 0xc2, 0xe4,
	0x7a, 0x80, 0x05, 0x26, 0x4a, 0xfa, 0xe8, 0xe6, 0x72, 0xe0, 0xf5, 0xcd, 0x1d, 0x62, 0x42, 0xa3,
	0x3f, 0xf4, 0xaf, 0x3c, 0xc7, 0xf5, 0x27, 0x5e, 0x6f, 0x60, 0x1a, 0x97, 0x43, 0xb0, 0x44, 0x16,
	0xdb, 0x8b, 0x75, 0x8a, 0x59, 0x82, 0x51, 0x8c, 0x99, 0x3d, 0x0f, 0x66, 0x19, 0x0b, 0x37, 0xfa,
	0xd4, 0xd6, 0x7f, 0x7f, 0x13, 0x33, 0xb9, 0x58, 0xcd, 0xec, 0x50, 0x2c, 0x3b, 0x0f, 0xa8, 0x9d,
	0x92, 0x5a, 0x2e, 0x7d, 0xde, 0x51, 0xd4, 0x59, 0xf9, 0x43, 0x78, 0xf7, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x04, 0x34, 0xea, 0xe3, 0x2f, 0x04, 0x00, 0x00,
}
